# Generated by Django 6.0.1 on 2026-01-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(choices=[('1mg', '1mg'), ('2mg', '2mg'), ('3mg', '3mg'), ('5mg', '5mg'), ('10mg', '10mg'), ('25mg', '25mg'), ('50mg', '50mg'), ('100mg', '100mg'), ('250mg', '250mg'), ('500mg', '500mg'), ('1000mg', '1000mg')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('refill_date', models.DateField()),
                ('refill_schedule', models.CharField(choices=[('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescriptions.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
    ]
